# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assuntos',
            fields=[
                ('id_assunto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'assuntos',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=2000)),
            ],
            options={
                'managed': False,
                'db_table': 'pergunta',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'resposta',
            },
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
