# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0002_auto_20170224_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'perguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'respostas',
                'managed': False,
            },
        ),
    ]
